name               = "forefathers-nutrition-api"
main               = "src/index.ts"
compatibility_date = "2026-05-01"

[[kv_namespaces]]
binding = "MENU_CACHE"
id      = "59df5dda46494a80a6c18180147a3e02"

[triggers]
crons = ["0 3 * * *"]
